version: "3"

services:
  web:
    image: shdv/File_encrypti_decrypt
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3991:80
    volumes:
      - ./src:/usr/share/nginx/html/out